### ISSUE TITLE
Disable "you do not have permission to browse the host file system" popup

### ISSUE THREAD

**Issue by arirawr** [MrVauxs/dnd5e-animations#10] opened 2023-04-17 10:04 UTC
> Sound effects with wildcards that play random sound variants require players to have Use File Browser permissions under core settings. To enable this, open your world and go to Game Settings, Configure Settings, All or Core, Open Permission Configuration, make sure all roles have Use File Browser checked.

I do not want my players to have access to the "Use File Browser" permission, and I am ok with not having sounds as a result.
However, even if I disable sounds in Sequencer, I still get the annoying popup about being unable to access the file system when a player triggers an animation.

Could you possibly add a global setting to the module to disable all sound triggering?

**Comment by MrVauxs** [comment] 2023-04-17 11:49
Overall, a duplicate of #8

**Closed by MrVauxs** 2023-04-17 11:49 UTC
