### ISSUE TITLE
Some sounds not matching expected location

### ISSUE THREAD

**Issue by T-Whiz** [MrVauxs/dnd5e-animations#5] opened 2023-03-13 17:52 UTC
version 1.1.1:

It looks like the following sounds may need to be updated in the file to match the assets location:

	x26 sounds/Weapons/Melee_Slashing_Piercing/
	should be sounds/Combat/Melee Slashing & Piercing/

	x16 sounds/Weapons/Melee_Bludgeoning/
	should be sounds/Combat/Melee Bludgeoning/

	x20 sounds/Weapons/Melee_Natural/
	should be sounds/Combat/Melee Natural/

	x10 sounds/Weapons/Melee_Miss/
	should be sounds/Combat/Melee Miss/
	
	x2 sounds/Weapons/Melee_Laser/
	should be sounds/Combat/Melee Laser/

	x2 sounds/Weapons/Ranged_Arrow_Fly-By/
	should be sounds/Combat/Arrow Fly-By/

	x4 sounds/Weapons/Ranged_Arrow_Impact/
	should be sounds/Combat/Arrow Impact/

	x1 sounds/Weapons/Ranged_Laser/
	should be sounds/Combat/Ranged Laser/

	x1 sounds/Combat/Ranged_Projectile/
	should be sounds/Combat/

	x1 sounds/Combat/whip-1.mp3
	not in assets

	x1 sounds/Combat/whip-2.mp3
	not in assets

	x2 sounds/creatures/laughter.mp3
	should be sounds/spells/Hideous-Laughter_Vicious-Mockery.mp3 (?)

	x1 sounds/Creatures/swallow.mp3
	should be sounds/Creatures/Swallow.mp3

	x2 sounds/Damage/Ice/
	should be sounds/Damage/Cold/

	x1 sounds/Ambience/church-bell.mp3
	not in assets
	should this be assets/sounds/Spells/Toll-the-Dead.mp3 (?)

	x1 sounds/Ambience/grinding-gears.mp3
	not in assets

	x1 sounds/Ambience/knocking.mp3
	not in assets
	should this be assets/sounds/Spells/Knock.mp3 ??

	x1 assets/fire-flamethrower-1.mp3
	should be assets/sounds/Damage/Fire/fire-flamethrower-1.mp3

**Comment by MrVauxs** [comment] 2023-03-13 17:56
Duplicate of #4.

**Closed by MrVauxs** 2023-03-13 17:56 UTC
